#!/usr/bin/env node
// German pack generator — hand-curated core (2026.07 seed, IDs preserved)
// plus a model-authored expansion (2026.08) pending human spot-review
// (docs/pack-review-2026.08.md). The full FrequencyWords-driven pipeline
// (docs/plan/07-content-pipeline.md, `packtool author`) is still pending;
// band assignment here is frequency-informed but hand-ordered.
//
// Authoring rules honored (docs/plan/07 stages 1–3):
// - Sense stability: no polysemous English sources ("bank", "light", "may",
//   "when", "no", "still", "left"…) and no English noun/verb homographs
//   whose verb use is common ("work", "play", "call", "run", "love"…).
// - Inflection safety: ambient items are invariants (conjunctions, adverbs,
//   prepositions, interjections, numerals), nouns with the full D10
//   determiner/number variant set, and fixed chunks. NO standalone verbs —
//   verb value ships as collocation chunks (OP-1 approach C).
// - Weekday/month/proper-like nouns swap 1:1 and are authored `exact` so
//   the D10 determiner-set requirement (which would read unnaturally,
//   "the Monday") doesn't apply; gender still rides in targetMeta.
//
// Usage: node build-seed.mjs > ../../build/de-2026.09.json

const slug = (s) =>
  s.toLowerCase()
    .replaceAll("ä", "ae").replaceAll("ö", "oe").replaceAll("ü", "ue").replaceAll("ß", "ss")
    .replaceAll(/[^a-z0-9]+/g, "-");

const level = (band) => (band <= 3 ? "a1" : band <= 6 ? "a2" : "b1");

const enIndefinite = (en) => (/^(hour|honest|heir)/i.test(en) || /^[aeiou]/i.test(en) ? "an" : "a");

// Noun with full determiner/number variant set (decision D10).
// `enAliases` adds parallel English sources (film/movie) with their own
// full variant sets pointing at the same German forms.
function noun({ en, enAliases = [], enPlAliases = [], de, gender, enPl, dePl, band, explanation, example }) {
  const indef = gender === "die" ? "eine" : "ein";
  const forms = [];
  for (const source of [en, ...enAliases]) {
    forms.push({ form: `the ${source}`, target: `${gender} ${de}` });
    forms.push({ form: `${enIndefinite(source)} ${source}`, target: `${indef} ${de}` });
    forms.push({ form: source, target: de });
  }
  if (enPl && dePl) {
    for (const pl of [enPl, ...enPlAliases]) {
      forms.push({ form: pl, target: dePl });
      forms.push({ form: `the ${pl}`, target: `die ${dePl}` });
    }
  }
  return {
    id: `de.word.${slug(de)}`,
    language: "de", kind: "word",
    sourceForms: forms,
    target: de,
    targetMeta: { gender, plural: dePl ?? null, pos: "noun", pronunciation: null },
    level: level(band), frequencyBand: band,
    replacementPolicy: "ambientSafe", fidelityTier: "formMatched",
    dependencies: [],
    explanation,
    examples: [example],
  };
}

// Invariant word (conjunction / adverb / preposition / numeral /
// interjection) — fidelity: exact. `enForms` allows several English
// sources mapping to the same invariant German word.
function inv({ en, enForms, de, pos, band, explanation, example, gender = null }) {
  const sources = enForms ?? [en];
  return {
    id: `de.word.${slug(de)}`,
    language: "de", kind: "word",
    sourceForms: sources.map((form) => ({ form, target: de })),
    target: de,
    targetMeta: { gender, plural: null, pos, pronunciation: null },
    level: level(band), frequencyBand: band,
    replacementPolicy: "ambientSafe", fidelityTier: "exact",
    dependencies: [],
    explanation,
    examples: [example],
  };
}

// Fixed chunk — fidelity: exact.
function chunk({ en, enForms, de, band, explanation, example, deps = [] }) {
  const sources = enForms ?? [en];
  return {
    id: `de.chunk.${slug(de)}`,
    language: "de", kind: "chunk",
    sourceForms: sources.map((form) => ({ form, target: de })),
    target: de,
    targetMeta: { gender: null, plural: null, pos: "chunk", pronunciation: null },
    level: level(band), frequencyBand: band,
    replacementPolicy: "ambientSafe", fidelityTier: "exact",
    dependencies: deps,
    explanation,
    examples: [example],
  };
}

const items = [
  // ══════════════════════════════════════════════════════════════════
  // Band 1 — unchanged from the 2026.07 seed (12 items, IDs stable)
  // ══════════════════════════════════════════════════════════════════
  inv({ en: "and", de: "und", pos: "conjunction", band: 1,
    explanation: "und means and — the most common German word.",
    example: { source: "Bread and butter.", target: "Brot und Butter." } }),
  inv({ en: "but", de: "aber", pos: "conjunction", band: 1,
    explanation: "aber means but.",
    example: { source: "I am coming, but later.", target: "Ich komme, aber später." } }),
  inv({ en: "or", de: "oder", pos: "conjunction", band: 1,
    explanation: "oder means or.",
    example: { source: "Coffee or tea?", target: "Kaffee oder Tee?" } }),
  inv({ en: "also", de: "auch", pos: "adverb", band: 1,
    explanation: "auch means also / too.",
    example: { source: "Me too.", target: "Ich auch." } }),
  inv({ en: "not", de: "nicht", pos: "adverb", band: 1,
    explanation: "nicht negates a statement: not.",
    example: { source: "That is not good.", target: "Das ist nicht gut." } }),
  inv({ en: "here", de: "hier", pos: "adverb", band: 1,
    explanation: "hier means here.",
    example: { source: "We are here.", target: "Wir sind hier." } }),
  inv({ en: "now", de: "jetzt", pos: "adverb", band: 1,
    explanation: "jetzt means now.",
    example: { source: "We are going now.", target: "Wir gehen jetzt." } }),
  inv({ en: "today", de: "heute", pos: "adverb", band: 1,
    explanation: "heute means today.",
    example: { source: "Today is Monday.", target: "Heute ist Montag." } }),
  noun({ en: "house", de: "Haus", gender: "das", enPl: "houses", dePl: "Häuser", band: 1,
    explanation: "das Haus (neuter) — house; plural Häuser.",
    example: { source: "The house is old.", target: "Das Haus ist alt." } }),
  noun({ en: "dog", de: "Hund", gender: "der", enPl: "dogs", dePl: "Hunde", band: 1,
    explanation: "der Hund (masculine) — dog; plural Hunde.",
    example: { source: "The dog is sleeping.", target: "Der Hund schläft." } }),
  noun({ en: "water", de: "Wasser", gender: "das", band: 1,
    explanation: "das Wasser (neuter) — water.",
    example: { source: "The water is cold.", target: "Das Wasser ist kalt." } }),
  noun({ en: "book", de: "Buch", gender: "das", enPl: "books", dePl: "Bücher", band: 1,
    explanation: "das Buch (neuter) — book; plural Bücher.",
    example: { source: "The book is good.", target: "Das Buch ist gut." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 2 — 2026.07 seed (14) + high-frequency invariants (6)
  // ══════════════════════════════════════════════════════════════════
  inv({ en: "always", de: "immer", pos: "adverb", band: 2,
    explanation: "immer means always.",
    example: { source: "It is always like that.", target: "Es ist immer so." } }),
  inv({ en: "often", de: "oft", pos: "adverb", band: 2,
    explanation: "oft means often.",
    example: { source: "We see that often.", target: "Wir sehen das oft." } }),
  inv({ en: "never", de: "nie", pos: "adverb", band: 2,
    explanation: "nie means never.",
    example: { source: "That never happens.", target: "Das passiert nie." } }),
  inv({ en: "again", de: "wieder", pos: "adverb", band: 2,
    explanation: "wieder means again.",
    example: { source: "We will see each other again.", target: "Wir sehen uns wieder." } }),
  inv({ en: "very", de: "sehr", pos: "adverb", band: 2,
    explanation: "sehr means very.",
    example: { source: "Thank you very much.", target: "Danke sehr." } }),
  inv({ en: "maybe", enForms: ["maybe", "perhaps"], de: "vielleicht", pos: "adverb", band: 2,
    explanation: "vielleicht means maybe / perhaps.",
    example: { source: "Maybe tomorrow.", target: "Vielleicht morgen." } }),
  inv({ en: "tomorrow", de: "morgen", pos: "adverb", band: 2,
    explanation: "morgen means tomorrow.",
    example: { source: "See you tomorrow!", target: "Bis morgen!" } }),
  inv({ en: "yesterday", de: "gestern", pos: "adverb", band: 2,
    explanation: "gestern means yesterday.",
    example: { source: "Yesterday was Sunday.", target: "Gestern war Sonntag." } }),
  noun({ en: "city", de: "Stadt", gender: "die", enPl: "cities", dePl: "Städte", band: 2,
    explanation: "die Stadt (feminine) — city; plural Städte.",
    example: { source: "The city is big.", target: "Die Stadt ist groß." } }),
  noun({ en: "child", de: "Kind", gender: "das", enPl: "children", dePl: "Kinder", band: 2,
    explanation: "das Kind (neuter) — child; plural Kinder.",
    example: { source: "The child is laughing.", target: "Das Kind lacht." } }),
  noun({ en: "friend", de: "Freund", gender: "der", enPl: "friends", dePl: "Freunde", band: 2,
    explanation: "der Freund (masculine) — friend; plural Freunde.",
    example: { source: "My friend lives here.", target: "Mein Freund wohnt hier." } }),
  noun({ en: "year", de: "Jahr", gender: "das", enPl: "years", dePl: "Jahre", band: 2,
    explanation: "das Jahr (neuter) — year; plural Jahre.",
    example: { source: "A year has twelve months.", target: "Ein Jahr hat zwölf Monate." } }),
  chunk({ en: "there is", enForms: ["there is", "there are"], de: "es gibt", band: 2,
    explanation: "es gibt is the fixed phrase for 'there is / there are'.",
    example: { source: "There is a lot to see.", target: "Es gibt viel zu sehen." } }),
  chunk({ en: "for example", de: "zum Beispiel", band: 2,
    explanation: "zum Beispiel means for example (abbreviated z. B.).",
    example: { source: "Many cities, for example Berlin.", target: "Viele Städte, zum Beispiel Berlin." } }),
  inv({ en: "with", de: "mit", pos: "preposition", band: 2,
    explanation: "mit means with.",
    example: { source: "Coffee with milk.", target: "Kaffee mit Milch." } }),
  inv({ en: "without", de: "ohne", pos: "preposition", band: 2,
    explanation: "ohne means without.",
    example: { source: "Without you it is boring.", target: "Ohne dich ist es langweilig." } }),
  inv({ en: "yes", de: "ja", pos: "interjection", band: 2,
    explanation: "ja means yes.",
    example: { source: "Yes, gladly!", target: "Ja, gerne!" } }),
  inv({ en: "please", de: "bitte", pos: "interjection", band: 2,
    explanation: "bitte means please (and 'you're welcome').",
    example: { source: "One coffee, please.", target: "Einen Kaffee, bitte." } }),
  inv({ en: "hello", de: "hallo", pos: "interjection", band: 2,
    explanation: "hallo means hello.",
    example: { source: "Hello, how are you?", target: "Hallo, wie geht's?" } }),
  inv({ en: "really", de: "wirklich", pos: "adverb", band: 2,
    explanation: "wirklich means really / truly.",
    example: { source: "That is really good.", target: "Das ist wirklich gut." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 3 — 2026.07 seed (13) + question words, everyday nouns, chunk
  // ══════════════════════════════════════════════════════════════════
  inv({ en: "nevertheless", de: "trotzdem", pos: "adverb", band: 3,
    explanation: "trotzdem means nevertheless / anyway.",
    example: { source: "It is raining; we are going nevertheless.", target: "Es regnet, trotzdem gehen wir." } }),
  inv({ en: "therefore", de: "deshalb", pos: "adverb", band: 3,
    explanation: "deshalb means therefore / that is why.",
    example: { source: "That is why I am here.", target: "Deshalb bin ich hier." } }),
  inv({ en: "almost", de: "fast", pos: "adverb", band: 3,
    explanation: "fast means almost.",
    example: { source: "It is almost done.", target: "Es ist fast fertig." } }),
  inv({ en: "only", de: "nur", pos: "adverb", band: 3,
    explanation: "nur means only.",
    example: { source: "Only today.", target: "Nur heute." } }),
  inv({ en: "already", de: "schon", pos: "adverb", band: 3,
    explanation: "schon means already.",
    example: { source: "I am already there.", target: "Ich bin schon da." } }),
  inv({ en: "together", de: "zusammen", pos: "adverb", band: 3,
    explanation: "zusammen means together.",
    example: { source: "We are here together.", target: "Wir sind zusammen hier." } }),
  inv({ en: "soon", de: "bald", pos: "adverb", band: 3,
    explanation: "bald means soon.",
    example: { source: "See you soon!", target: "Bis bald!" } }),
  inv({ en: "unfortunately", de: "leider", pos: "adverb", band: 3,
    explanation: "leider means unfortunately.",
    example: { source: "Unfortunately not.", target: "Leider nein." } }),
  noun({ en: "world", de: "Welt", gender: "die", enPl: "worlds", dePl: "Welten", band: 3,
    explanation: "die Welt (feminine) — world; plural Welten.",
    example: { source: "The world is small.", target: "Die Welt ist klein." } }),
  noun({ en: "night", de: "Nacht", gender: "die", enPl: "nights", dePl: "Nächte", band: 3,
    explanation: "die Nacht (feminine) — night; plural Nächte.",
    example: { source: "The night was long.", target: "Die Nacht war lang." } }),
  noun({ en: "door", de: "Tür", gender: "die", enPl: "doors", dePl: "Türen", band: 3,
    explanation: "die Tür (feminine) — door; plural Türen.",
    example: { source: "The door is open.", target: "Die Tür ist offen." } }),
  noun({ en: "hand", de: "Hand", gender: "die", enPl: "hands", dePl: "Hände", band: 3,
    explanation: "die Hand (feminine) — hand; plural Hände.",
    example: { source: "My hand is cold.", target: "Meine Hand ist kalt." } }),
  chunk({ en: "of course", de: "natürlich", band: 3,
    explanation: "natürlich as a sentence word means of course.",
    example: { source: "Of course I am coming.", target: "Natürlich komme ich." } }),
  inv({ en: "where", de: "wo", pos: "adverb", band: 3,
    explanation: "wo asks where.",
    example: { source: "Where are you?", target: "Wo bist du?" } }),
  inv({ en: "how", de: "wie", pos: "adverb", band: 3,
    explanation: "wie asks how (and makes comparisons).",
    example: { source: "How does that work?", target: "Wie funktioniert das?" } }),
  inv({ en: "why", de: "warum", pos: "adverb", band: 3,
    explanation: "warum asks why.",
    example: { source: "Why not?", target: "Warum nicht?" } }),
  noun({ en: "man", de: "Mann", gender: "der", enPl: "men", dePl: "Männer", band: 3,
    explanation: "der Mann (masculine) — man; plural Männer.",
    example: { source: "The man is reading.", target: "Der Mann liest." } }),
  noun({ en: "woman", de: "Frau", gender: "die", enPl: "women", dePl: "Frauen", band: 3,
    explanation: "die Frau (feminine) — woman; plural Frauen (also Mrs/Ms).",
    example: { source: "The woman is speaking.", target: "Die Frau spricht." } }),
  noun({ en: "car", de: "Auto", gender: "das", enPl: "cars", dePl: "Autos", band: 3,
    explanation: "das Auto (neuter) — car; plural Autos.",
    example: { source: "The car is new.", target: "Das Auto ist neu." } }),
  noun({ en: "street", de: "Straße", gender: "die", enPl: "streets", dePl: "Straßen", band: 3,
    explanation: "die Straße (feminine) — street; plural Straßen.",
    example: { source: "The street is quiet.", target: "Die Straße ist ruhig." } }),
  noun({ en: "money", de: "Geld", gender: "das", band: 3,
    explanation: "das Geld (neuter) — money.",
    example: { source: "Money is not everything.", target: "Geld ist nicht alles." } }),
  noun({ en: "food", de: "Essen", gender: "das", band: 3,
    explanation: "das Essen (neuter) — food / the meal.",
    example: { source: "The food is ready.", target: "Das Essen ist fertig." } }),
  noun({ en: "school", de: "Schule", gender: "die", enPl: "schools", dePl: "Schulen", band: 3,
    explanation: "die Schule (feminine) — school; plural Schulen.",
    example: { source: "The school is closed today.", target: "Die Schule ist heute geschlossen." } }),
  chunk({ en: "I think", de: "ich glaube", band: 3,
    explanation: "ich glaube means I think / I believe.",
    example: { source: "I think that is right.", target: "Ich glaube, das stimmt." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 4 — 2026.07 seed (15) + family, language, indefinites, chunks
  // ══════════════════════════════════════════════════════════════════
  inv({ en: "actually", de: "eigentlich", pos: "adverb", band: 4,
    explanation: "eigentlich means actually / in fact.",
    example: { source: "Actually yes.", target: "Eigentlich ja." } }),
  inv({ en: "exactly", de: "genau", pos: "adverb", band: 4,
    explanation: "genau means exactly — also used alone as agreement.",
    example: { source: "Exactly!", target: "Genau!" } }),
  inv({ en: "immediately", enForms: ["immediately", "right away"], de: "sofort", pos: "adverb", band: 4,
    explanation: "sofort means immediately / right away.",
    example: { source: "I am coming immediately.", target: "Ich komme sofort." } }),
  inv({ en: "finally", de: "endlich", pos: "adverb", band: 4,
    explanation: "endlich means finally / at last.",
    example: { source: "Finally the weekend!", target: "Endlich Wochenende!" } }),
  inv({ en: "sometimes", de: "manchmal", pos: "adverb", band: 4,
    explanation: "manchmal means sometimes.",
    example: { source: "Sometimes it rains.", target: "Manchmal regnet es." } }),
  inv({ en: "everywhere", de: "überall", pos: "adverb", band: 4,
    explanation: "überall means everywhere.",
    example: { source: "Water is everywhere.", target: "Wasser ist überall." } }),
  inv({ en: "at first", de: "zuerst", pos: "adverb", band: 4,
    explanation: "zuerst means (at) first.",
    example: { source: "Breakfast first.", target: "Zuerst das Frühstück." } }),
  inv({ en: "by the way", de: "übrigens", pos: "adverb", band: 4,
    explanation: "übrigens means by the way.",
    example: { source: "By the way, thanks.", target: "Übrigens, danke." } }),
  noun({ en: "time", de: "Zeit", gender: "die", enPl: "times", dePl: "Zeiten", band: 4,
    explanation: "die Zeit (feminine) — time; plural Zeiten.",
    example: { source: "I have no time.", target: "Ich habe keine Zeit." } }),
  noun({ en: "day", de: "Tag", gender: "der", enPl: "days", dePl: "Tage", band: 4,
    explanation: "der Tag (masculine) — day; plural Tage.",
    example: { source: "The day starts early.", target: "Der Tag beginnt früh." } }),
  noun({ en: "week", de: "Woche", gender: "die", enPl: "weeks", dePl: "Wochen", band: 4,
    explanation: "die Woche (feminine) — week; plural Wochen.",
    example: { source: "The week has seven days.", target: "Die Woche hat sieben Tage." } }),
  noun({ en: "month", de: "Monat", gender: "der", enPl: "months", dePl: "Monate", band: 4,
    explanation: "der Monat (masculine) — month; plural Monate.",
    example: { source: "The month is almost over.", target: "Der Monat ist fast vorbei." } }),
  chunk({ en: "good morning", de: "guten Morgen", band: 4,
    explanation: "guten Morgen is the standard morning greeting.",
    example: { source: "Good morning, how are you?", target: "Guten Morgen, wie geht's?" } }),
  chunk({ en: "thank you", de: "danke", band: 4,
    explanation: "danke means thank you.",
    example: { source: "Thank you for everything.", target: "Danke für alles." } }),
  chunk({ en: "see you soon", de: "bis bald", band: 4, deps: ["de.word.bald"],
    explanation: "bis bald means see you soon.",
    example: { source: "See you soon, Anna!", target: "Bis bald, Anna!" } }),
  noun({ en: "mother", de: "Mutter", gender: "die", enPl: "mothers", dePl: "Mütter", band: 4,
    explanation: "die Mutter (feminine) — mother; plural Mütter.",
    example: { source: "My mother is calling.", target: "Meine Mutter ruft an." } }),
  noun({ en: "father", de: "Vater", gender: "der", enPl: "fathers", dePl: "Väter", band: 4,
    explanation: "der Vater (masculine) — father; plural Väter.",
    example: { source: "My father cooks well.", target: "Mein Vater kocht gut." } }),
  noun({ en: "brother", de: "Bruder", gender: "der", enPl: "brothers", dePl: "Brüder", band: 4,
    explanation: "der Bruder (masculine) — brother; plural Brüder.",
    example: { source: "My brother is older.", target: "Mein Bruder ist älter." } }),
  noun({ en: "sister", de: "Schwester", gender: "die", enPl: "sisters", dePl: "Schwestern", band: 4,
    explanation: "die Schwester (feminine) — sister; plural Schwestern.",
    example: { source: "My sister lives in Berlin.", target: "Meine Schwester wohnt in Berlin." } }),
  noun({ en: "family", de: "Familie", gender: "die", enPl: "families", dePl: "Familien", band: 4,
    explanation: "die Familie (feminine) — family; plural Familien.",
    example: { source: "The family is eating together.", target: "Die Familie isst zusammen." } }),
  noun({ en: "evening", de: "Abend", gender: "der", enPl: "evenings", dePl: "Abende", band: 4,
    explanation: "der Abend (masculine) — evening; plural Abende.",
    example: { source: "The evening was lovely.", target: "Der Abend war schön." } }),
  noun({ en: "name", de: "Name", gender: "der", enPl: "names", dePl: "Namen", band: 4,
    explanation: "der Name (masculine) — name; plural Namen.",
    example: { source: "The name is easy.", target: "Der Name ist einfach." } }),
  noun({ en: "word", de: "Wort", gender: "das", enPl: "words", dePl: "Wörter", band: 4,
    explanation: "das Wort (neuter) — word; plural Wörter.",
    example: { source: "A new word every day.", target: "Jeden Tag ein neues Wort." } }),
  noun({ en: "language", de: "Sprache", gender: "die", enPl: "languages", dePl: "Sprachen", band: 4,
    explanation: "die Sprache (feminine) — language; plural Sprachen.",
    example: { source: "German is a beautiful language.", target: "Deutsch ist eine schöne Sprache." } }),
  noun({ en: "question", de: "Frage", gender: "die", enPl: "questions", dePl: "Fragen", band: 4,
    explanation: "die Frage (feminine) — question; plural Fragen.",
    example: { source: "Good question!", target: "Gute Frage!" } }),
  inv({ en: "something", de: "etwas", pos: "pronoun", band: 4,
    explanation: "etwas means something — it never changes form.",
    example: { source: "Something is missing.", target: "Etwas fehlt." } }),
  inv({ en: "nothing", de: "nichts", pos: "pronoun", band: 4,
    explanation: "nichts means nothing — it never changes form.",
    example: { source: "Nothing happened.", target: "Nichts ist passiert." } }),
  inv({ en: "more", de: "mehr", pos: "adverb", band: 4,
    explanation: "mehr means more.",
    example: { source: "More coffee, please.", target: "Mehr Kaffee, bitte." } }),
  chunk({ en: "I know", de: "ich weiß", band: 4,
    explanation: "ich weiß means I know.",
    example: { source: "I know, I know.", target: "Ich weiß, ich weiß." } }),
  chunk({ en: "I don't know", de: "ich weiß nicht", band: 4,
    explanation: "ich weiß nicht means I don't know.",
    example: { source: "I don't know, sorry.", target: "Ich weiß nicht, tut mir leid." } }),
  chunk({ en: "at home", de: "zu Hause", band: 4,
    explanation: "zu Hause means at home.",
    example: { source: "I am staying at home today.", target: "Ich bleibe heute zu Hause." } }),
  chunk({ en: "me too", de: "ich auch", band: 4, deps: ["de.word.auch"],
    explanation: "ich auch means me too.",
    example: { source: "Me too, actually.", target: "Ich auch, eigentlich." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 5 — home & table nouns, numbers 2–10, pace adverbs, greetings
  // ══════════════════════════════════════════════════════════════════
  noun({ en: "table", de: "Tisch", gender: "der", enPl: "tables", dePl: "Tische", band: 5,
    explanation: "der Tisch (masculine) — table; plural Tische.",
    example: { source: "The table is round.", target: "Der Tisch ist rund." } }),
  noun({ en: "chair", de: "Stuhl", gender: "der", enPl: "chairs", dePl: "Stühle", band: 5,
    explanation: "der Stuhl (masculine) — chair; plural Stühle.",
    example: { source: "The chair is free.", target: "Der Stuhl ist frei." } }),
  noun({ en: "room", de: "Zimmer", gender: "das", enPl: "rooms", dePl: "Zimmer", band: 5,
    explanation: "das Zimmer (neuter) — room; the plural is also Zimmer.",
    example: { source: "The room is bright.", target: "Das Zimmer ist hell." } }),
  noun({ en: "window", de: "Fenster", gender: "das", enPl: "windows", dePl: "Fenster", band: 5,
    explanation: "das Fenster (neuter) — window; the plural is also Fenster.",
    example: { source: "The window is open.", target: "Das Fenster ist offen." } }),
  noun({ en: "bread", de: "Brot", gender: "das", enPl: "breads", dePl: "Brote", band: 5,
    explanation: "das Brot (neuter) — bread; plural Brote.",
    example: { source: "Fresh bread smells wonderful.", target: "Frisches Brot riecht wunderbar." } }),
  noun({ en: "milk", de: "Milch", gender: "die", band: 5,
    explanation: "die Milch (feminine) — milk.",
    example: { source: "The milk is fresh.", target: "Die Milch ist frisch." } }),
  noun({ en: "coffee", de: "Kaffee", gender: "der", band: 5,
    explanation: "der Kaffee (masculine) — coffee.",
    example: { source: "The coffee is hot.", target: "Der Kaffee ist heiß." } }),
  noun({ en: "tea", de: "Tee", gender: "der", band: 5,
    explanation: "der Tee (masculine) — tea.",
    example: { source: "Tea with honey helps.", target: "Tee mit Honig hilft." } }),
  noun({ en: "apple", de: "Apfel", gender: "der", enPl: "apples", dePl: "Äpfel", band: 5,
    explanation: "der Apfel (masculine) — apple; plural Äpfel.",
    example: { source: "An apple a day.", target: "Ein Apfel am Tag." } }),
  noun({ en: "teacher", de: "Lehrer", gender: "der", enPl: "teachers", dePl: "Lehrer", band: 5,
    explanation: "der Lehrer (masculine) — teacher; the plural is also Lehrer.",
    example: { source: "The teacher explains it.", target: "Der Lehrer erklärt es." } }),
  inv({ en: "two", de: "zwei", pos: "numeral", band: 5,
    explanation: "zwei means two.",
    example: { source: "Two coffees, please.", target: "Zwei Kaffee, bitte." } }),
  inv({ en: "three", de: "drei", pos: "numeral", band: 5,
    explanation: "drei means three.",
    example: { source: "Three days to go.", target: "Noch drei Tage." } }),
  inv({ en: "four", de: "vier", pos: "numeral", band: 5,
    explanation: "vier means four.",
    example: { source: "Four seasons.", target: "Vier Jahreszeiten." } }),
  inv({ en: "five", de: "fünf", pos: "numeral", band: 5,
    explanation: "fünf means five.",
    example: { source: "Five minutes, please.", target: "Fünf Minuten, bitte." } }),
  inv({ en: "six", de: "sechs", pos: "numeral", band: 5,
    explanation: "sechs means six.",
    example: { source: "Six euros, please.", target: "Sechs Euro, bitte." } }),
  inv({ en: "seven", de: "sieben", pos: "numeral", band: 5,
    explanation: "sieben means seven.",
    example: { source: "Seven days a week.", target: "Sieben Tage die Woche." } }),
  inv({ en: "eight", de: "acht", pos: "numeral", band: 5,
    explanation: "acht means eight.",
    example: { source: "Eight hours of sleep.", target: "Acht Stunden Schlaf." } }),
  inv({ en: "nine", de: "neun", pos: "numeral", band: 5,
    explanation: "neun means nine.",
    example: { source: "Nine o'clock works.", target: "Neun Uhr passt." } }),
  inv({ en: "ten", de: "zehn", pos: "numeral", band: 5,
    explanation: "zehn means ten.",
    example: { source: "Ten new words.", target: "Zehn neue Wörter." } }),
  inv({ en: "however", de: "jedoch", pos: "adverb", band: 5,
    explanation: "jedoch means however.",
    example: { source: "However, that takes time.", target: "Das braucht jedoch Zeit." } }),
  inv({ en: "especially", de: "besonders", pos: "adverb", band: 5,
    explanation: "besonders means especially / particularly.",
    example: { source: "Especially in winter.", target: "Besonders im Winter." } }),
  inv({ en: "quickly", de: "schnell", pos: "adverb", band: 5,
    explanation: "schnell means quickly / fast.",
    example: { source: "That went quickly.", target: "Das ging schnell." } }),
  inv({ en: "slowly", de: "langsam", pos: "adverb", band: 5,
    explanation: "langsam means slowly.",
    example: { source: "Please speak slowly.", target: "Bitte langsam sprechen." } }),
  inv({ en: "excuse me", enForms: ["excuse me", "sorry"], de: "Entschuldigung", pos: "interjection", band: 5,
    explanation: "Entschuldigung means excuse me / sorry.",
    example: { source: "Excuse me, where is the station?", target: "Entschuldigung, wo ist der Bahnhof?" } }),
  chunk({ en: "I would like", de: "ich möchte", band: 5,
    explanation: "ich möchte means I would like — the polite way to ask.",
    example: { source: "I would like a tea.", target: "Ich möchte einen Tee." } }),
  chunk({ en: "good evening", de: "guten Abend", band: 5, deps: ["de.word.abend"],
    explanation: "guten Abend is the evening greeting.",
    example: { source: "Good evening, everyone.", target: "Guten Abend, alle zusammen." } }),
  chunk({ en: "good night", de: "gute Nacht", band: 5, deps: ["de.word.nacht"],
    explanation: "gute Nacht is said before sleep.",
    example: { source: "Good night, sleep well.", target: "Gute Nacht, schlaf gut." } }),
  chunk({ en: "see you later", de: "bis später", band: 5,
    explanation: "bis später means see you later.",
    example: { source: "See you later, then.", target: "Bis später dann." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 6 — weekdays, time nouns, big numbers, stance adverbs, chunks
  // ══════════════════════════════════════════════════════════════════
  inv({ en: "Monday", de: "Montag", pos: "noun", gender: "der", band: 6,
    explanation: "der Montag — Monday. Days of the week are masculine.",
    example: { source: "Monday is quiet.", target: "Der Montag ist ruhig." } }),
  inv({ en: "Tuesday", de: "Dienstag", pos: "noun", gender: "der", band: 6,
    explanation: "der Dienstag — Tuesday.",
    example: { source: "Tuesday works for me.", target: "Dienstag passt mir." } }),
  inv({ en: "Wednesday", de: "Mittwoch", pos: "noun", gender: "der", band: 6,
    explanation: "der Mittwoch — Wednesday (literally 'mid-week').",
    example: { source: "Wednesday is the middle.", target: "Mittwoch ist die Mitte." } }),
  inv({ en: "Thursday", de: "Donnerstag", pos: "noun", gender: "der", band: 6,
    explanation: "der Donnerstag — Thursday ('thunder day').",
    example: { source: "Thursday evening, then.", target: "Donnerstag Abend also." } }),
  inv({ en: "Friday", de: "Freitag", pos: "noun", gender: "der", band: 6,
    explanation: "der Freitag — Friday.",
    example: { source: "Finally Friday!", target: "Endlich Freitag!" } }),
  inv({ en: "Saturday", de: "Samstag", pos: "noun", gender: "der", band: 6,
    explanation: "der Samstag — Saturday.",
    example: { source: "Saturday we sleep in.", target: "Samstag schlafen wir aus." } }),
  inv({ en: "Sunday", de: "Sonntag", pos: "noun", gender: "der", band: 6,
    explanation: "der Sonntag — Sunday.",
    example: { source: "Sunday is for resting.", target: "Sonntag ist zum Ausruhen." } }),
  noun({ en: "hour", de: "Stunde", gender: "die", enPl: "hours", dePl: "Stunden", band: 6,
    explanation: "die Stunde (feminine) — hour; plural Stunden.",
    example: { source: "An hour later.", target: "Eine Stunde später." } }),
  noun({ en: "minute", de: "Minute", gender: "die", enPl: "minutes", dePl: "Minuten", band: 6,
    explanation: "die Minute (feminine) — minute; plural Minuten.",
    example: { source: "One minute, please.", target: "Eine Minute, bitte." } }),
  noun({ en: "moment", de: "Moment", gender: "der", enPl: "moments", dePl: "Momente", band: 6,
    explanation: "der Moment (masculine) — moment; plural Momente.",
    example: { source: "A moment, please.", target: "Einen Moment, bitte." } }),
  noun({ en: "colour", enAliases: ["color"], enPlAliases: ["colors"], de: "Farbe", gender: "die", enPl: "colours", dePl: "Farben", band: 6,
    explanation: "die Farbe (feminine) — colour; plural Farben.",
    example: { source: "The colour is beautiful.", target: "Die Farbe ist schön." } }),
  inv({ en: "hundred", de: "hundert", pos: "numeral", band: 6,
    explanation: "hundert means hundred.",
    example: { source: "A hundred words already.", target: "Schon hundert Wörter." } }),
  inv({ en: "thousand", de: "tausend", pos: "numeral", band: 6,
    explanation: "tausend means thousand.",
    example: { source: "A thousand thanks.", target: "Tausend Dank." } }),
  inv({ en: "between", de: "zwischen", pos: "preposition", band: 6,
    explanation: "zwischen means between.",
    example: { source: "Between two worlds.", target: "Zwischen zwei Welten." } }),
  inv({ en: "probably", de: "wahrscheinlich", pos: "adverb", band: 6,
    explanation: "wahrscheinlich means probably.",
    example: { source: "Probably tomorrow.", target: "Wahrscheinlich morgen." } }),
  inv({ en: "suddenly", de: "plötzlich", pos: "adverb", band: 6,
    explanation: "plötzlich means suddenly.",
    example: { source: "Suddenly it was quiet.", target: "Plötzlich war es still." } }),
  inv({ en: "rarely", enForms: ["rarely", "seldom"], de: "selten", pos: "adverb", band: 6,
    explanation: "selten means rarely / seldom.",
    example: { source: "That happens rarely.", target: "Das passiert selten." } }),
  inv({ en: "outside", de: "draußen", pos: "adverb", band: 6,
    explanation: "draußen means outside (as a place).",
    example: { source: "The children are outside.", target: "Die Kinder sind draußen." } }),
  inv({ en: "less", de: "weniger", pos: "adverb", band: 6,
    explanation: "weniger means less / fewer.",
    example: { source: "Less is more.", target: "Weniger ist mehr." } }),
  chunk({ en: "no idea", de: "keine Ahnung", band: 6,
    explanation: "keine Ahnung means no idea.",
    example: { source: "No idea, honestly.", target: "Keine Ahnung, ehrlich." } }),
  chunk({ en: "how are you", de: "wie geht's", band: 6, deps: ["de.word.wie"],
    explanation: "wie geht's is the casual how are you.",
    example: { source: "Hi! How are you?", target: "Hallo! Wie geht's?" } }),
  chunk({ en: "tonight", de: "heute Abend", band: 6, deps: ["de.word.heute", "de.word.abend"],
    explanation: "heute Abend means tonight (literally 'today evening').",
    example: { source: "See you tonight.", target: "Bis heute Abend." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 7 — abstract & media nouns, place adverbs, chunks (B1 begins)
  // ══════════════════════════════════════════════════════════════════
  noun({ en: "problem", de: "Problem", gender: "das", enPl: "problems", dePl: "Probleme", band: 7,
    explanation: "das Problem (neuter) — problem; plural Probleme.",
    example: { source: "The problem is small.", target: "Das Problem ist klein." } }),
  noun({ en: "idea", de: "Idee", gender: "die", enPl: "ideas", dePl: "Ideen", band: 7,
    explanation: "die Idee (feminine) — idea; plural Ideen.",
    example: { source: "An idea is forming.", target: "Eine Idee entsteht." } }),
  noun({ en: "life", de: "Leben", gender: "das", band: 7,
    explanation: "das Leben (neuter) — life.",
    example: { source: "Life is short.", target: "Das Leben ist kurz." } }),
  noun({ en: "end", de: "Ende", gender: "das", enPl: "ends", dePl: "Enden", band: 7,
    explanation: "das Ende (neuter) — end; plural Enden.",
    example: { source: "The end is near.", target: "Das Ende ist nah." } }),
  noun({ en: "beginning", de: "Anfang", gender: "der", enPl: "beginnings", dePl: "Anfänge", band: 7,
    explanation: "der Anfang (masculine) — beginning; plural Anfänge.",
    example: { source: "A good beginning.", target: "Ein guter Anfang." } }),
  noun({ en: "picture", de: "Bild", gender: "das", enPl: "pictures", dePl: "Bilder", band: 7,
    explanation: "das Bild (neuter) — picture / image; plural Bilder.",
    example: { source: "The picture hangs crooked.", target: "Das Bild hängt schief." } }),
  noun({ en: "film", enAliases: ["movie"], enPlAliases: ["movies"], de: "Film", gender: "der", enPl: "films", dePl: "Filme", band: 7,
    explanation: "der Film (masculine) — film / movie; plural Filme.",
    example: { source: "The film starts at eight.", target: "Der Film beginnt um acht." } }),
  noun({ en: "game", de: "Spiel", gender: "das", enPl: "games", dePl: "Spiele", band: 7,
    explanation: "das Spiel (neuter) — game; plural Spiele.",
    example: { source: "The game is over.", target: "Das Spiel ist vorbei." } }),
  noun({ en: "person", de: "Person", gender: "die", enPl: "persons", dePl: "Personen", band: 7,
    explanation: "die Person (feminine) — person; plural Personen.",
    example: { source: "A friendly person.", target: "Eine freundliche Person." } }),
  { // die Leute — plural-only noun; determiner form carries the D10 duty.
    id: "de.word.leute",
    language: "de", kind: "word",
    sourceForms: [
      { form: "people", target: "Leute" },
      { form: "the people", target: "die Leute" },
    ],
    target: "Leute",
    targetMeta: { gender: "die", plural: "Leute", pos: "noun", pronunciation: null },
    level: "b1", frequencyBand: 7,
    replacementPolicy: "ambientSafe", fidelityTier: "formMatched",
    dependencies: [],
    explanation: "die Leute (plural only) — people.",
    examples: [{ source: "The people are waiting.", target: "Die Leute warten." }],
  },
  noun({ en: "message", de: "Nachricht", gender: "die", enPl: "messages", dePl: "Nachrichten", band: 7,
    explanation: "die Nachricht (feminine) — message; plural Nachrichten (also 'the news').",
    example: { source: "A new message arrived.", target: "Eine neue Nachricht kam an." } }),
  noun({ en: "telephone", de: "Telefon", gender: "das", enPl: "telephones", dePl: "Telefone", band: 7,
    explanation: "das Telefon (neuter) — telephone; plural Telefone.",
    example: { source: "The telephone is ringing.", target: "Das Telefon klingelt." } }),
  noun({ en: "computer", de: "Computer", gender: "der", enPl: "computers", dePl: "Computer", band: 7,
    explanation: "der Computer (masculine) — computer; the plural is also Computer.",
    example: { source: "The computer is slow today.", target: "Der Computer ist heute langsam." } }),
  inv({ en: "somewhere", de: "irgendwo", pos: "adverb", band: 7,
    explanation: "irgendwo means somewhere.",
    example: { source: "Somewhere in the city.", target: "Irgendwo in der Stadt." } }),
  inv({ en: "upstairs", de: "oben", pos: "adverb", band: 7,
    explanation: "oben means upstairs / up top.",
    example: { source: "The bathroom is upstairs.", target: "Das Bad ist oben." } }),
  inv({ en: "downstairs", de: "unten", pos: "adverb", band: 7,
    explanation: "unten means downstairs / below.",
    example: { source: "The kitchen is downstairs.", target: "Die Küche ist unten." } }),
  inv({ en: "anyway", de: "sowieso", pos: "adverb", band: 7,
    explanation: "sowieso means anyway / in any case.",
    example: { source: "I was going anyway.", target: "Ich wollte sowieso gehen." } }),
  chunk({ en: "no problem", de: "kein Problem", band: 7, deps: ["de.word.problem"],
    explanation: "kein Problem means no problem.",
    example: { source: "No problem at all.", target: "Gar kein Problem." } }),
  chunk({ en: "too much", de: "zu viel", band: 7,
    explanation: "zu viel means too much.",
    example: { source: "That is too much.", target: "Das ist zu viel." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 8 — reasons & journeys, months, more connective glue
  // ══════════════════════════════════════════════════════════════════
  noun({ en: "reason", de: "Grund", gender: "der", enPl: "reasons", dePl: "Gründe", band: 8,
    explanation: "der Grund (masculine) — reason; plural Gründe.",
    example: { source: "A good reason.", target: "Ein guter Grund." } }),
  noun({ en: "example", de: "Beispiel", gender: "das", enPl: "examples", dePl: "Beispiele", band: 8,
    explanation: "das Beispiel (neuter) — example; plural Beispiele.",
    example: { source: "An example helps.", target: "Ein Beispiel hilft." } }),
  noun({ en: "story", enAliases: ["history"], de: "Geschichte", gender: "die", enPl: "stories", dePl: "Geschichten", band: 8,
    explanation: "die Geschichte (feminine) — story, and also history; plural Geschichten.",
    example: { source: "A long story.", target: "Eine lange Geschichte." } }),
  noun({ en: "journey", enAliases: ["trip"], enPlAliases: ["trips"], de: "Reise", gender: "die", enPl: "journeys", dePl: "Reisen", band: 8,
    explanation: "die Reise (feminine) — journey / trip; plural Reisen.",
    example: { source: "The journey begins.", target: "Die Reise beginnt." } }),
  noun({ en: "goal", de: "Ziel", gender: "das", enPl: "goals", dePl: "Ziele", band: 8,
    explanation: "das Ziel (neuter) — goal / destination; plural Ziele.",
    example: { source: "The goal is close.", target: "Das Ziel ist nah." } }),
  noun({ en: "email", de: "E-Mail", gender: "die", enPl: "emails", dePl: "E-Mails", band: 8,
    explanation: "die E-Mail (feminine) — email; plural E-Mails.",
    example: { source: "An email from Anna.", target: "Eine E-Mail von Anna." } }),
  noun({ en: "internet", de: "Internet", gender: "das", band: 8,
    explanation: "das Internet (neuter) — the internet.",
    example: { source: "The internet is down.", target: "Das Internet ist weg." } }),
  noun({ en: "sport", de: "Sport", gender: "der", band: 8,
    explanation: "der Sport (masculine) — sport.",
    example: { source: "Sport keeps you fit.", target: "Sport hält fit." } }),
  inv({ en: "January", de: "Januar", pos: "noun", gender: "der", band: 8,
    explanation: "der Januar — January. Months are masculine.",
    example: { source: "January is cold.", target: "Der Januar ist kalt." } }),
  inv({ en: "February", de: "Februar", pos: "noun", gender: "der", band: 8,
    explanation: "der Februar — February.",
    example: { source: "February is short.", target: "Der Februar ist kurz." } }),
  inv({ en: "April", de: "April", pos: "noun", gender: "der", band: 8,
    explanation: "der April — April.",
    example: { source: "April does what it wants.", target: "April macht, was er will." } }),
  inv({ en: "June", de: "Juni", pos: "noun", gender: "der", band: 8,
    explanation: "der Juni — June.",
    example: { source: "June is warm.", target: "Der Juni ist warm." } }),
  inv({ en: "July", de: "Juli", pos: "noun", gender: "der", band: 8,
    explanation: "der Juli — July.",
    example: { source: "July is holiday time.", target: "Der Juli ist Urlaubszeit." } }),
  inv({ en: "August", de: "August", pos: "noun", gender: "der", band: 8,
    explanation: "der August — August.",
    example: { source: "August is the hottest.", target: "Der August ist am heißesten." } }),
  inv({ en: "September", de: "September", pos: "noun", gender: "der", band: 8,
    explanation: "der September — September.",
    example: { source: "September feels new.", target: "Der September fühlt sich neu an." } }),
  inv({ en: "October", de: "Oktober", pos: "noun", gender: "der", band: 8,
    explanation: "der Oktober — October.",
    example: { source: "October is golden.", target: "Der Oktober ist golden." } }),
  inv({ en: "November", de: "November", pos: "noun", gender: "der", band: 8,
    explanation: "der November — November.",
    example: { source: "November is grey.", target: "Der November ist grau." } }),
  inv({ en: "December", de: "Dezember", pos: "noun", gender: "der", band: 8,
    explanation: "der Dezember — December.",
    example: { source: "December smells of cinnamon.", target: "Der Dezember riecht nach Zimt." } }),
  inv({ en: "during", de: "während", pos: "preposition", band: 8,
    explanation: "während means during.",
    example: { source: "During the week.", target: "Während der Woche." } }),
  inv({ en: "the day after tomorrow", enForms: ["the day after tomorrow", "day after tomorrow"], de: "übermorgen", pos: "adverb", band: 8,
    explanation: "übermorgen means the day after tomorrow — one word in German.",
    example: { source: "See you the day after tomorrow.", target: "Bis übermorgen." } }),
  chunk({ en: "in any case", enForms: ["in any case", "definitely"], de: "auf jeden Fall", band: 8,
    explanation: "auf jeden Fall means in any case / definitely.",
    example: { source: "In any case, I am coming.", target: "Auf jeden Fall komme ich." } }),
  chunk({ en: "luckily", enForms: ["luckily", "fortunately"], de: "zum Glück", band: 8,
    explanation: "zum Glück means luckily / fortunately.",
    example: { source: "Luckily it stayed dry.", target: "Zum Glück blieb es trocken." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 9 — places around town, weather
  // ══════════════════════════════════════════════════════════════════
  noun({ en: "train station", de: "Bahnhof", gender: "der", enPl: "train stations", dePl: "Bahnhöfe", band: 9,
    explanation: "der Bahnhof (masculine) — train station; plural Bahnhöfe.",
    example: { source: "The train station is central.", target: "Der Bahnhof ist zentral." } }),
  noun({ en: "airport", de: "Flughafen", gender: "der", enPl: "airports", dePl: "Flughäfen", band: 9,
    explanation: "der Flughafen (masculine) — airport; plural Flughäfen.",
    example: { source: "The airport is far away.", target: "Der Flughafen ist weit weg." } }),
  noun({ en: "hotel", de: "Hotel", gender: "das", enPl: "hotels", dePl: "Hotels", band: 9,
    explanation: "das Hotel (neuter) — hotel; plural Hotels.",
    example: { source: "The hotel is booked.", target: "Das Hotel ist ausgebucht." } }),
  noun({ en: "restaurant", de: "Restaurant", gender: "das", enPl: "restaurants", dePl: "Restaurants", band: 9,
    explanation: "das Restaurant (neuter) — restaurant; plural Restaurants.",
    example: { source: "The restaurant is full.", target: "Das Restaurant ist voll." } }),
  noun({ en: "market", de: "Markt", gender: "der", enPl: "markets", dePl: "Märkte", band: 9,
    explanation: "der Markt (masculine) — market; plural Märkte.",
    example: { source: "The market opens early.", target: "Der Markt öffnet früh." } }),
  noun({ en: "church", de: "Kirche", gender: "die", enPl: "churches", dePl: "Kirchen", band: 9,
    explanation: "die Kirche (feminine) — church; plural Kirchen.",
    example: { source: "The church is old.", target: "Die Kirche ist alt." } }),
  noun({ en: "hospital", de: "Krankenhaus", gender: "das", enPl: "hospitals", dePl: "Krankenhäuser", band: 9,
    explanation: "das Krankenhaus (neuter) — hospital ('sick house'); plural Krankenhäuser.",
    example: { source: "The hospital is nearby.", target: "Das Krankenhaus ist in der Nähe." } }),
  noun({ en: "library", de: "Bibliothek", gender: "die", enPl: "libraries", dePl: "Bibliotheken", band: 9,
    explanation: "die Bibliothek (feminine) — library; plural Bibliotheken.",
    example: { source: "The library is quiet.", target: "Die Bibliothek ist leise." } }),
  noun({ en: "garden", de: "Garten", gender: "der", enPl: "gardens", dePl: "Gärten", band: 9,
    explanation: "der Garten (masculine) — garden; plural Gärten.",
    example: { source: "The garden is blooming.", target: "Der Garten blüht." } }),
  noun({ en: "park", de: "Park", gender: "der", enPl: "parks", dePl: "Parks", band: 9,
    explanation: "der Park (masculine) — park; plural Parks.",
    example: { source: "The park is green.", target: "Der Park ist grün." } }),
  noun({ en: "weather", de: "Wetter", gender: "das", band: 9,
    explanation: "das Wetter (neuter) — weather.",
    example: { source: "The weather is lovely.", target: "Das Wetter ist herrlich." } }),
  noun({ en: "sun", de: "Sonne", gender: "die", band: 9,
    explanation: "die Sonne (feminine) — sun.",
    example: { source: "The sun is shining.", target: "Die Sonne scheint." } }),
  noun({ en: "snow", de: "Schnee", gender: "der", band: 9,
    explanation: "der Schnee (masculine) — snow.",
    example: { source: "Fresh snow everywhere.", target: "Überall frischer Schnee." } }),
  noun({ en: "wind", de: "Wind", gender: "der", band: 9,
    explanation: "der Wind (masculine) — wind.",
    example: { source: "The wind is strong.", target: "Der Wind ist stark." } }),
  inv({ en: "the day before yesterday", enForms: ["the day before yesterday", "day before yesterday"], de: "vorgestern", pos: "adverb", band: 9,
    explanation: "vorgestern means the day before yesterday — one word in German.",
    example: { source: "That was the day before yesterday.", target: "Das war vorgestern." } }),

  // ══════════════════════════════════════════════════════════════════
  // Band 10 — nature, animals, body, one profession
  // ══════════════════════════════════════════════════════════════════
  noun({ en: "mountain", de: "Berg", gender: "der", enPl: "mountains", dePl: "Berge", band: 10,
    explanation: "der Berg (masculine) — mountain; plural Berge.",
    example: { source: "The mountain is high.", target: "Der Berg ist hoch." } }),
  noun({ en: "river", de: "Fluss", gender: "der", enPl: "rivers", dePl: "Flüsse", band: 10,
    explanation: "der Fluss (masculine) — river; plural Flüsse.",
    example: { source: "The river is wide.", target: "Der Fluss ist breit." } }),
  noun({ en: "lake", de: "See", gender: "der", enPl: "lakes", dePl: "Seen", band: 10,
    explanation: "der See (masculine) — lake; plural Seen.",
    example: { source: "The lake is calm.", target: "Der See ist ruhig." } }),
  noun({ en: "sea", de: "Meer", gender: "das", enPl: "seas", dePl: "Meere", band: 10,
    explanation: "das Meer (neuter) — sea; plural Meere.",
    example: { source: "The sea is deep.", target: "Das Meer ist tief." } }),
  noun({ en: "forest", de: "Wald", gender: "der", enPl: "forests", dePl: "Wälder", band: 10,
    explanation: "der Wald (masculine) — forest; plural Wälder.",
    example: { source: "The forest is dark.", target: "Der Wald ist dunkel." } }),
  noun({ en: "tree", de: "Baum", gender: "der", enPl: "trees", dePl: "Bäume", band: 10,
    explanation: "der Baum (masculine) — tree; plural Bäume.",
    example: { source: "The tree is ancient.", target: "Der Baum ist uralt." } }),
  noun({ en: "flower", de: "Blume", gender: "die", enPl: "flowers", dePl: "Blumen", band: 10,
    explanation: "die Blume (feminine) — flower; plural Blumen.",
    example: { source: "A flower for you.", target: "Eine Blume für dich." } }),
  noun({ en: "bird", de: "Vogel", gender: "der", enPl: "birds", dePl: "Vögel", band: 10,
    explanation: "der Vogel (masculine) — bird; plural Vögel.",
    example: { source: "The bird is singing.", target: "Der Vogel singt." } }),
  noun({ en: "cat", de: "Katze", gender: "die", enPl: "cats", dePl: "Katzen", band: 10,
    explanation: "die Katze (feminine) — cat; plural Katzen.",
    example: { source: "The cat is sleeping.", target: "Die Katze schläft." } }),
  noun({ en: "horse", de: "Pferd", gender: "das", enPl: "horses", dePl: "Pferde", band: 10,
    explanation: "das Pferd (neuter) — horse; plural Pferde.",
    example: { source: "The horse is fast.", target: "Das Pferd ist schnell." } }),
  noun({ en: "fish", de: "Fisch", gender: "der", enPl: "fishes", dePl: "Fische", band: 10,
    explanation: "der Fisch (masculine) — fish; plural Fische.",
    example: { source: "The fish is fresh.", target: "Der Fisch ist frisch." } }),
  noun({ en: "head", de: "Kopf", gender: "der", enPl: "heads", dePl: "Köpfe", band: 10,
    explanation: "der Kopf (masculine) — head; plural Köpfe.",
    example: { source: "My head is buzzing.", target: "Mein Kopf brummt." } }),
  noun({ en: "eye", de: "Auge", gender: "das", enPl: "eyes", dePl: "Augen", band: 10,
    explanation: "das Auge (neuter) — eye; plural Augen.",
    example: { source: "An eye for detail.", target: "Ein Auge fürs Detail." } }),
  noun({ en: "ear", de: "Ohr", gender: "das", enPl: "ears", dePl: "Ohren", band: 10,
    explanation: "das Ohr (neuter) — ear; plural Ohren.",
    example: { source: "An open ear.", target: "Ein offenes Ohr." } }),
  noun({ en: "nose", de: "Nase", gender: "die", enPl: "noses", dePl: "Nasen", band: 10,
    explanation: "die Nase (feminine) — nose; plural Nasen.",
    example: { source: "The nose is cold.", target: "Die Nase ist kalt." } }),
  noun({ en: "mouth", de: "Mund", gender: "der", enPl: "mouths", dePl: "Münder", band: 10,
    explanation: "der Mund (masculine) — mouth; plural Münder.",
    example: { source: "Open your mouth, please.", target: "Den Mund öffnen, bitte." } }),
  noun({ en: "heart", de: "Herz", gender: "das", enPl: "hearts", dePl: "Herzen", band: 10,
    explanation: "das Herz (neuter) — heart; plural Herzen.",
    example: { source: "The heart beats faster.", target: "Das Herz schlägt schneller." } }),
  noun({ en: "doctor", de: "Arzt", gender: "der", enPl: "doctors", dePl: "Ärzte", band: 10,
    explanation: "der Arzt (masculine) — doctor; plural Ärzte.",
    example: { source: "The doctor is coming.", target: "Der Arzt kommt." } }),
];

// ══════════════════════════════════════════════════════════════════
// Rich examples (2026.09, redesign D-R4): two extra authored examples
// per item, merged below — three total each, so cloze/rebuild stop
// recycling one sentence. Guards enforce what the engine needs: the
// German sentence carries the citation form (recall display + the
// validator's contains check), the English sentence carries a source
// form verbatim (day-1 cloze can blank it), and 3–10 whitespace tokens
// keep every sentence a buildable rebuild puzzle.
const e = (source, target) => ({ source, target });

const extraExamples = {
  "de.word.und": [e("Coffee and cake.", "Kaffee und Kuchen."), e("You and I stay here.", "Du und ich bleiben hier.")],
  "de.word.aber": [e("Small, but nice.", "Klein, aber fein."), e("I am tired, but happy.", "Ich bin müde, aber glücklich.")],
  "de.word.oder": [e("Now or never.", "Jetzt oder nie."), e("Are we walking or driving?", "Gehen wir oder fahren wir?")],
  "de.word.auch": [e("My sister is also coming.", "Meine Schwester kommt auch."), e("That is also possible.", "Das ist auch möglich.")],
  "de.word.nicht": [e("I do not know that.", "Das weiß ich nicht."), e("The water is not warm.", "Das Wasser ist nicht warm.")],
  "de.word.hier": [e("The bakery here is good.", "Die Bäckerei hier ist gut."), e("Here it is quiet.", "Hier ist es ruhig.")],
  "de.word.jetzt": [e("The film starts now.", "Der Film beginnt jetzt."), e("Now I understand.", "Jetzt verstehe ich.")],
  "de.word.heute": [e("Today the sun is shining.", "Heute scheint die Sonne."), e("What are we doing today?", "Was machen wir heute?")],
  "de.word.haus": [e("The house has a garden.", "Das Haus hat einen Garten."), e("We are buying a house.", "Wir kaufen ein Haus.")],
  "de.word.hund": [e("The dog wants to go outside.", "Der Hund will nach draußen."), e("A dog is waiting at the door.", "Ein Hund wartet an der Tür.")],
  "de.word.wasser": [e("A glass of water, please.", "Ein Glas Wasser, bitte."), e("The water in the lake is clear.", "Das Wasser im See ist klar.")],
  "de.word.buch": [e("I am reading a good book.", "Ich lese ein gutes Buch."), e("The book is on the table.", "Das Buch liegt auf dem Tisch.")],
  "de.word.immer": [e("It is always cold here.", "Hier ist es immer kalt."), e("She always comes on time.", "Sie kommt immer pünktlich.")],
  "de.word.oft": [e("We often eat pasta.", "Wir essen oft Nudeln."), e("It often rains in April.", "Im April regnet es oft.")],
  "de.word.nie": [e("I never drink coffee.", "Ich trinke nie Kaffee."), e("It is never too late.", "Es ist nie zu spät.")],
  "de.word.wieder": [e("It is raining again.", "Es regnet wieder."), e("We will try it again.", "Wir versuchen es wieder.")],
  "de.word.sehr": [e("The city is very old.", "Die Stadt ist sehr alt."), e("I like that very much.", "Das gefällt mir sehr.")],
  "de.word.vielleicht": [e("Maybe it will rain.", "Vielleicht regnet es."), e("Maybe he is right.", "Vielleicht hat er recht.")],
  "de.word.morgen": [e("Tomorrow is a new day.", "Morgen ist ein neuer Tag."), e("We are driving to Berlin tomorrow.", "Wir fahren morgen nach Berlin.")],
  "de.word.gestern": [e("Yesterday I was at home.", "Gestern war ich zu Hause."), e("The letter arrived yesterday.", "Der Brief kam gestern an.")],
  "de.word.stadt": [e("The city never sleeps.", "Die Stadt schläft nie."), e("We live near the city.", "Wir wohnen nahe der Stadt.")],
  "de.word.kind": [e("The child is playing in the garden.", "Das Kind spielt im Garten."), e("A child is singing.", "Ein Kind singt.")],
  "de.word.freund": [e("A friend is helping me.", "Ein Freund hilft mir."), e("My friend cooks for us.", "Mein Freund kocht für uns.")],
  "de.word.jahr": [e("The year is going by quickly.", "Das Jahr vergeht schnell."), e("Next year we are travelling.", "Nächstes Jahr reisen wir.")],
  "de.chunk.es-gibt": [e("There is a problem.", "Es gibt ein Problem."), e("There is nothing new.", "Es gibt nichts Neues.")],
  "de.chunk.zum-beispiel": [e("Animals, for example cats and dogs.", "Tiere, zum Beispiel Katzen und Hunde."), e("For example on Sunday.", "Zum Beispiel am Sonntag.")],
  "de.word.mit": [e("We are driving with the car.", "Wir fahren mit dem Auto."), e("Tea with milk, please.", "Tee mit Milch, bitte.")],
  "de.word.ohne": [e("Coffee without sugar, please.", "Kaffee ohne Zucker, bitte."), e("We are going without him.", "Wir gehen ohne ihn.")],
  "de.word.ja": [e("Yes, that works.", "Ja, das passt."), e("Yes, I am coming along.", "Ja, ich komme mit.")],
  "de.word.bitte": [e("Two tickets, please.", "Zwei Karten, bitte."), e("Please wait here.", "Bitte hier warten.")],
  "de.word.hallo": [e("Hello, nice to meet you.", "Hallo, schön dich kennenzulernen."), e("Hello, is anyone there?", "Hallo, ist da jemand?")],
  "de.word.wirklich": [e("Is that really true?", "Ist das wirklich wahr?"), e("The food is really tasty.", "Das Essen ist wirklich lecker.")],
  "de.word.trotzdem": [e("It is late; we are staying nevertheless.", "Es ist spät, trotzdem bleiben wir."), e("He is tired; he works nevertheless.", "Er ist müde, trotzdem arbeitet er.")],
  "de.word.deshalb": [e("It is cold, therefore we are staying inside.", "Es ist kalt, deshalb bleiben wir drinnen."), e("Therefore we are starting early.", "Deshalb beginnen wir früh.")],
  "de.word.fast": [e("It is almost midnight.", "Es ist fast Mitternacht."), e("Almost everyone is here.", "Fast alle sind da.")],
  "de.word.nur": [e("It costs only two euros.", "Es kostet nur zwei Euro."), e("Only one question, please.", "Nur eine Frage, bitte.")],
  "de.word.schon": [e("The bus is already here.", "Der Bus ist schon da."), e("It is already late.", "Es ist schon spät.")],
  "de.word.zusammen": [e("We are cooking together today.", "Wir kochen heute zusammen."), e("Together it goes faster.", "Zusammen geht es schneller.")],
  "de.word.bald": [e("The train is coming soon.", "Der Zug kommt bald."), e("It will soon be winter.", "Bald ist Winter.")],
  "de.word.leider": [e("Unfortunately I have no time.", "Leider habe ich keine Zeit."), e("The shop is unfortunately closed.", "Der Laden ist leider zu.")],
  "de.word.welt": [e("The world is changing.", "Die Welt verändert sich."), e("A map of the world.", "Eine Karte der Welt.")],
  "de.word.nacht": [e("The night is quiet.", "Die Nacht ist still."), e("We are driving through the night.", "Wir fahren durch die Nacht.")],
  "de.word.tuer": [e("Please close the door.", "Bitte die Tür schließen."), e("The door is locked.", "Die Tür ist abgeschlossen.")],
  "de.word.hand": [e("Give me your hand.", "Gib mir deine Hand."), e("He is waving with his hand.", "Er winkt mit der Hand.")],
  "de.chunk.natuerlich": [e("Of course that works.", "Natürlich geht das."), e("Of course you can come along.", "Natürlich kannst du mitkommen.")],
  "de.word.wo": [e("Where is the station?", "Wo ist der Bahnhof?"), e("Where do you live now?", "Wo wohnst du jetzt?")],
  "de.word.wie": [e("How was your day?", "Wie war dein Tag?"), e("How do you say that?", "Wie sagt man das?")],
  "de.word.warum": [e("Why are you laughing?", "Warum lachst du?"), e("Why is it so quiet?", "Warum ist es so leise?")],
  "de.word.mann": [e("The man is waiting outside.", "Der Mann wartet draußen."), e("An old man is sitting there.", "Ein alter Mann sitzt dort.")],
  "de.word.frau": [e("The woman is laughing loudly.", "Die Frau lacht laut."), e("A woman is asking for directions.", "Eine Frau fragt nach dem Weg.")],
  "de.word.auto": [e("The car will not start.", "Das Auto springt nicht an."), e("We are washing the car.", "Wir waschen das Auto.")],
  "de.word.strasse": [e("The street is wet.", "Die Straße ist nass."), e("We live on this street.", "Wir wohnen in dieser Straße.")],
  "de.word.geld": [e("The money is not enough.", "Das Geld reicht nicht."), e("He is saving money for a trip.", "Er spart Geld für eine Reise.")],
  "de.word.essen": [e("The food smells wonderful.", "Das Essen riecht wunderbar."), e("The food is getting cold.", "Das Essen wird kalt.")],
  "de.word.schule": [e("The school starts at eight.", "Die Schule beginnt um acht."), e("The children are going to school.", "Die Kinder gehen zur Schule.")],
  "de.chunk.ich-glaube": [e("I think it will work.", "Ich glaube, es klappt."), e("I think he is at home.", "Ich glaube, er ist zu Hause.")],
  "de.word.eigentlich": [e("Actually I wanted to sleep.", "Eigentlich wollte ich schlafen."), e("What is that actually?", "Was ist das eigentlich?")],
  "de.word.genau": [e("That is exactly right.", "Das ist genau richtig."), e("Exactly at nine o'clock.", "Genau um neun Uhr.")],
  "de.word.sofort": [e("Please come immediately.", "Bitte komm sofort."), e("The taxi is coming immediately.", "Das Taxi kommt sofort.")],
  "de.word.endlich": [e("Finally it is warm.", "Endlich ist es warm."), e("Finally you are here!", "Endlich bist du da!")],
  "de.word.manchmal": [e("Sometimes I forget that.", "Manchmal vergesse ich das."), e("Sometimes less is more.", "Manchmal ist weniger mehr.")],
  "de.word.ueberall": [e("There are flowers everywhere.", "Überall sind Blumen."), e("I looked everywhere.", "Ich habe überall gesucht.")],
  "de.word.zuerst": [e("At first it was strange.", "Zuerst war es seltsam."), e("At first we drink coffee.", "Zuerst trinken wir Kaffee.")],
  "de.word.uebrigens": [e("By the way, the film was great.", "Übrigens, der Film war super."), e("By the way, Anna is coming too.", "Übrigens kommt Anna auch.")],
  "de.word.zeit": [e("Time goes by quickly.", "Die Zeit vergeht schnell."), e("We have enough time.", "Wir haben genug Zeit.")],
  "de.word.tag": [e("The day was long.", "Der Tag war lang."), e("A beautiful day begins.", "Ein schöner Tag beginnt.")],
  "de.word.woche": [e("The week is almost over.", "Die Woche ist fast vorbei."), e("Next week it will start.", "Nächste Woche geht es los.")],
  "de.word.monat": [e("The month has thirty days.", "Der Monat hat dreißig Tage."), e("The month begins on a Monday.", "Der Monat beginnt am Montag.")],
  "de.chunk.guten-morgen": [e("Good morning, the coffee is ready.", "Guten Morgen, der Kaffee ist fertig."), e("Good morning, did you sleep well?", "Guten Morgen, hast du gut geschlafen?")],
  "de.chunk.danke": [e("Thank you for the help.", "Danke für die Hilfe."), e("Thank you, that is kind.", "Danke, das ist lieb.")],
  "de.chunk.bis-bald": [e("See you soon, take care!", "Bis bald, mach's gut!"), e("Bye, see you soon!", "Tschüss, bis bald!")],
  "de.word.mutter": [e("My mother bakes bread.", "Meine Mutter backt Brot."), e("The mother is singing quietly.", "Die Mutter singt leise.")],
  "de.word.vater": [e("My father reads the newspaper.", "Mein Vater liest die Zeitung."), e("The father is playing with the child.", "Der Vater spielt mit dem Kind.")],
  "de.word.bruder": [e("My brother lives in Hamburg.", "Mein Bruder wohnt in Hamburg."), e("Her brother is very tall.", "Ihr Bruder ist sehr groß.")],
  "de.word.schwester": [e("My sister is studying medicine.", "Meine Schwester studiert Medizin."), e("His sister is calling.", "Seine Schwester ruft an.")],
  "de.word.familie": [e("The family is travelling by train.", "Die Familie fährt mit dem Zug."), e("A big family lives here.", "Eine große Familie wohnt hier.")],
  "de.word.abend": [e("The evening is still young.", "Der Abend ist noch jung."), e("In the evening we cook.", "Am Abend kochen wir.")],
  "de.word.name": [e("What is your name?", "Wie ist dein Name?"), e("The name sounds familiar.", "Der Name klingt bekannt.")],
  "de.word.wort": [e("A word says a lot.", "Ein Wort sagt viel."), e("What does this word mean?", "Was bedeutet dieses Wort?")],
  "de.word.sprache": [e("The language sounds soft.", "Die Sprache klingt weich."), e("Every language has rules.", "Jede Sprache hat Regeln.")],
  "de.word.frage": [e("I have a question.", "Ich habe eine Frage."), e("The question is easy.", "Die Frage ist leicht.")],
  "de.word.etwas": [e("I would like to eat something.", "Ich möchte etwas essen."), e("Something is different today.", "Etwas ist heute anders.")],
  "de.word.nichts": [e("I see nothing.", "Ich sehe nichts."), e("Nothing lasts forever.", "Nichts hält ewig.")],
  "de.word.mehr": [e("I need more time.", "Ich brauche mehr Zeit."), e("More light, please.", "Mehr Licht, bitte.")],
  "de.chunk.ich-weiss": [e("I know where that is.", "Ich weiß, wo das ist."), e("I know what you mean.", "Ich weiß, was du meinst.")],
  "de.chunk.ich-weiss-nicht": [e("I don't know why.", "Ich weiß nicht, warum."), e("I don't know if that works.", "Ich weiß nicht, ob das geht.")],
  "de.chunk.zu-hause": [e("We are staying at home tonight.", "Wir bleiben heute Abend zu Hause."), e("At home it is nicest.", "Zu Hause ist es am schönsten.")],
  "de.chunk.ich-auch": [e("Me too, of course.", "Ich auch, natürlich."), e("Me too, probably.", "Ich auch, wahrscheinlich.")],
  "de.word.tisch": [e("The table is set.", "Der Tisch ist gedeckt."), e("The keys are on the table.", "Die Schlüssel liegen auf dem Tisch.")],
  "de.word.stuhl": [e("The chair is comfortable.", "Der Stuhl ist bequem."), e("Please take a chair.", "Nimm dir bitte einen Stuhl.")],
  "de.word.zimmer": [e("The room has two windows.", "Das Zimmer hat zwei Fenster."), e("The room is warm and quiet.", "Das Zimmer ist warm und ruhig.")],
  "de.word.fenster": [e("Please open the window.", "Bitte das Fenster öffnen."), e("The window looks onto the garden.", "Das Fenster geht zum Garten.")],
  "de.word.brot": [e("The bread is still warm.", "Das Brot ist noch warm."), e("We are buying bread at the market.", "Wir kaufen Brot auf dem Markt.")],
  "de.word.milch": [e("The milk is in the fridge.", "Die Milch steht im Kühlschrank."), e("Coffee with warm milk.", "Kaffee mit warmer Milch.")],
  "de.word.kaffee": [e("The coffee smells good.", "Der Kaffee riecht gut."), e("One more coffee, please.", "Noch einen Kaffee, bitte.")],
  "de.word.tee": [e("The tea is too hot.", "Der Tee ist zu heiß."), e("Green tea calms you.", "Grüner Tee beruhigt.")],
  "de.word.apfel": [e("The apple is sweet.", "Der Apfel ist süß."), e("An apple is lying in the bowl.", "Ein Apfel liegt in der Schale.")],
  "de.word.lehrer": [e("The teacher is patient.", "Der Lehrer ist geduldig."), e("Our teacher speaks clearly.", "Unser Lehrer spricht deutlich.")],
  "de.word.zwei": [e("We have two cats.", "Wir haben zwei Katzen."), e("Two minutes to go.", "Noch zwei Minuten.")],
  "de.word.drei": [e("Three apples, please.", "Drei Äpfel, bitte."), e("The child is three years old.", "Das Kind ist drei Jahre alt.")],
  "de.word.vier": [e("It is four o'clock.", "Es ist vier Uhr."), e("Four chairs at the table.", "Vier Stühle am Tisch.")],
  "de.word.fuenf": [e("Five days until the trip.", "Noch fünf Tage bis zur Reise."), e("We are meeting at five.", "Wir treffen uns um fünf.")],
  "de.word.sechs": [e("The train leaves at six.", "Der Zug fährt um sechs."), e("Six months already.", "Schon sechs Monate.")],
  "de.word.sieben": [e("The rainbow has seven colours.", "Sieben Farben hat der Regenbogen."), e("We are eating at seven.", "Wir essen um sieben.")],
  "de.word.acht": [e("The shop opens at eight.", "Der Laden öffnet um acht."), e("Eight euros, please.", "Acht Euro, bitte.")],
  "de.word.neun": [e("The course begins at nine.", "Der Kurs beginnt um neun."), e("Nine letters in one word.", "Neun Buchstaben in einem Wort.")],
  "de.word.zehn": [e("Ten minutes on foot.", "Zehn Minuten zu Fuß."), e("We are counting to ten.", "Wir zählen bis zehn.")],
  "de.word.jedoch": [e("However, it is expensive.", "Es ist jedoch teuer."), e("The plan, however, is good.", "Der Plan ist jedoch gut.")],
  "de.word.besonders": [e("The cake is especially tasty.", "Der Kuchen ist besonders lecker."), e("I especially like autumn.", "Ich mag den Herbst besonders.")],
  "de.word.schnell": [e("Come quickly, it is starting!", "Komm schnell, es fängt an!"), e("Children learn quickly.", "Kinder lernen schnell.")],
  "de.word.langsam": [e("Please drive slowly.", "Bitte langsam fahren."), e("We are walking home slowly.", "Wir gehen langsam nach Hause.")],
  "de.word.entschuldigung": [e("Excuse me, what time is it?", "Entschuldigung, wie spät ist es?"), e("Excuse me, is this seat free?", "Entschuldigung, ist der Platz frei?")],
  "de.chunk.ich-moechte": [e("I would like to pay.", "Ich möchte zahlen."), e("I would like a table for two.", "Ich möchte einen Tisch für zwei.")],
  "de.chunk.guten-abend": [e("Good evening, do come in.", "Guten Abend, kommen Sie herein."), e("Good evening, the table is ready.", "Guten Abend, der Tisch ist bereit.")],
  "de.chunk.gute-nacht": [e("Good night, see you tomorrow.", "Gute Nacht, bis morgen."), e("The children say good night.", "Die Kinder sagen gute Nacht.")],
  "de.chunk.bis-spaeter": [e("See you later at the park.", "Bis später im Park."), e("I have to go — see you later!", "Ich muss los — bis später!")],
  "de.word.montag": [e("On Monday the week begins.", "Am Montag beginnt die Woche."), e("Monday is market day.", "Montag ist Markttag.")],
  "de.word.dienstag": [e("On Tuesday I play football.", "Am Dienstag spiele ich Fußball."), e("Tuesday is training day.", "Dienstag ist Trainingstag.")],
  "de.word.mittwoch": [e("On Wednesday we cook together.", "Am Mittwoch kochen wir zusammen."), e("Wednesday is almost the weekend.", "Mittwoch ist fast Wochenende.")],
  "de.word.donnerstag": [e("On Thursday the market is open.", "Am Donnerstag ist der Markt offen."), e("Thursday suits everyone.", "Der Donnerstag passt allen.")],
  "de.word.freitag": [e("On Friday we celebrate.", "Am Freitag feiern wir."), e("Friday evening is free.", "Der Freitagabend ist frei.")],
  "de.word.samstag": [e("On Saturday we go to the market.", "Am Samstag gehen wir zum Markt."), e("Saturday is family day.", "Samstag ist Familientag.")],
  "de.word.sonntag": [e("On Sunday everything is closed.", "Am Sonntag ist alles zu."), e("Sunday begins slowly.", "Der Sonntag beginnt langsam.")],
  "de.word.stunde": [e("An hour has sixty minutes.", "Eine Stunde hat sechzig Minuten."), e("We are waiting one more hour.", "Wir warten noch eine Stunde.")],
  "de.word.minute": [e("A minute goes by quickly.", "Eine Minute vergeht schnell."), e("Every minute counts.", "Jede Minute zählt.")],
  "de.word.moment": [e("One moment, I am coming.", "Einen Moment, ich komme."), e("The moment was perfect.", "Der Moment war perfekt.")],
  "de.word.farbe": [e("Which colour do you like?", "Welche Farbe magst du?"), e("The colour is too dark.", "Die Farbe ist zu dunkel.")],
  "de.word.hundert": [e("A hundred people are waiting.", "Hundert Leute warten."), e("That costs a hundred euros.", "Das kostet hundert Euro.")],
  "de.word.tausend": [e("A thousand lights in the city.", "Tausend Lichter in der Stadt."), e("A thousand questions at once.", "Tausend Fragen auf einmal.")],
  "de.word.zwischen": [e("The café is between the bank and the park.", "Das Café liegt zwischen Bank und Park."), e("Between twelve and one we eat.", "Zwischen zwölf und eins essen wir.")],
  "de.word.wahrscheinlich": [e("It will probably rain.", "Wahrscheinlich regnet es."), e("She is probably right.", "Sie hat wahrscheinlich recht.")],
  "de.word.ploetzlich": [e("Suddenly the light went out.", "Plötzlich ging das Licht aus."), e("Suddenly everything happened fast.", "Plötzlich ging alles schnell.")],
  "de.word.selten": [e("He is rarely at home.", "Er ist selten zu Hause."), e("It rarely snows here.", "Hier schneit es selten.")],
  "de.word.draussen": [e("It is cold outside.", "Draußen ist es kalt."), e("We are eating outside today.", "Wir essen heute draußen.")],
  "de.word.weniger": [e("Less noise, please.", "Weniger Lärm, bitte."), e("It costs less than ten euros.", "Es kostet weniger als zehn Euro.")],
  "de.chunk.keine-ahnung": [e("No idea where he is.", "Keine Ahnung, wo er ist."), e("No idea, ask Anna.", "Keine Ahnung, frag Anna.")],
  "de.chunk.wie-geht-s": [e("How are you today?", "Wie geht's dir heute?"), e("Hello Anna, how are you?", "Hallo Anna, wie geht's?")],
  "de.chunk.heute-abend": [e("Tonight we are cooking pasta.", "Heute Abend kochen wir Nudeln."), e("What are you doing tonight?", "Was machst du heute Abend?")],
  "de.word.problem": [e("We are solving the problem together.", "Wir lösen das Problem zusammen."), e("A problem with the car.", "Ein Problem mit dem Auto.")],
  "de.word.idee": [e("The idea is brilliant.", "Die Idee ist genial."), e("I have an idea!", "Ich habe eine Idee!")],
  "de.word.leben": [e("Life goes on.", "Das Leben geht weiter."), e("A quiet life in the country.", "Ein ruhiges Leben auf dem Land.")],
  "de.word.ende": [e("At the end everything turned out fine.", "Am Ende wurde alles gut."), e("The end of the street.", "Das Ende der Straße.")],
  "de.word.anfang": [e("Every beginning is hard.", "Aller Anfang ist schwer."), e("At the beginning of the year.", "Am Anfang des Jahres.")],
  "de.word.bild": [e("The picture shows the sea.", "Das Bild zeigt das Meer."), e("A picture of the family.", "Ein Bild von der Familie.")],
  "de.word.film": [e("The film was exciting.", "Der Film war spannend."), e("We are watching a film tonight.", "Wir sehen heute Abend einen Film.")],
  "de.word.spiel": [e("The game begins at three.", "Das Spiel beginnt um drei."), e("A game for two people.", "Ein Spiel für zwei Personen.")],
  "de.word.person": [e("One person is still missing.", "Eine Person fehlt noch."), e("A table for one person.", "Ein Tisch für eine Person.")],
  "de.word.leute": [e("Many people know that.", "Viele Leute wissen das."), e("The people here are friendly.", "Die Leute hier sind freundlich.")],
  "de.word.nachricht": [e("The message was short.", "Die Nachricht war kurz."), e("Please send me a message.", "Schick mir bitte eine Nachricht.")],
  "de.word.telefon": [e("The telephone will not stop ringing.", "Das Telefon klingelt ohne Pause."), e("My telephone is off.", "Mein Telefon ist aus.")],
  "de.word.computer": [e("The computer needs an update.", "Der Computer braucht ein Update."), e("The new computer is quiet.", "Der neue Computer ist leise.")],
  "de.word.irgendwo": [e("Somewhere a dog is barking.", "Irgendwo bellt ein Hund."), e("The key is somewhere here.", "Der Schlüssel ist irgendwo hier.")],
  "de.word.oben": [e("The bedroom is upstairs.", "Das Schlafzimmer ist oben."), e("Upstairs it is warmer.", "Oben ist es wärmer.")],
  "de.word.unten": [e("The cellar is downstairs.", "Der Keller ist unten."), e("We are waiting downstairs.", "Wir warten unten.")],
  "de.word.sowieso": [e("It does not matter anyway.", "Das ist sowieso egal."), e("I am coming along anyway.", "Ich komme sowieso mit.")],
  "de.chunk.kein-problem": [e("No problem, I will help.", "Kein Problem, ich helfe."), e("That is no problem at all.", "Das ist gar kein Problem.")],
  "de.chunk.zu-viel": [e("Too much sugar in the tea.", "Zu viel Zucker im Tee."), e("That is far too much.", "Das ist viel zu viel.")],
  "de.word.grund": [e("There is no reason to worry.", "Es gibt keinen Grund zur Sorge."), e("The reason is simple.", "Der Grund ist einfach.")],
  "de.word.beispiel": [e("A good example helps a lot.", "Ein gutes Beispiel hilft viel."), e("Give me an example, please.", "Gib mir bitte ein Beispiel.")],
  "de.word.geschichte": [e("The story ends well.", "Die Geschichte endet gut."), e("Grandpa is telling a story.", "Opa erzählt eine Geschichte.")],
  "de.word.reise": [e("The journey was long.", "Die Reise war lang."), e("A journey through Europe.", "Eine Reise durch Europa.")],
  "de.word.ziel": [e("We are almost at the goal.", "Wir sind fast am Ziel."), e("The goal motivates us.", "Das Ziel motiviert uns.")],
  "de.word.e-mail": [e("The email is important.", "Die E-Mail ist wichtig."), e("I am writing an email.", "Ich schreibe eine E-Mail.")],
  "de.word.internet": [e("The internet is slow today.", "Das Internet ist heute langsam."), e("No internet in the forest.", "Kein Internet im Wald.")],
  "de.word.sport": [e("Sport is good for the heart.", "Sport ist gut fürs Herz."), e("On Tuesdays we do sport.", "Dienstags machen wir Sport.")],
  "de.word.januar": [e("In January it often snows.", "Im Januar schneit es oft."), e("January begins quietly.", "Der Januar beginnt ruhig.")],
  "de.word.februar": [e("In February it stays cold.", "Im Februar bleibt es kalt."), e("February is the shortest month.", "Der Februar ist der kürzeste Monat.")],
  "de.word.april": [e("In April everything blooms.", "Im April blüht alles."), e("April brings rain and sun.", "Der April bringt Regen und Sonne.")],
  "de.word.juni": [e("In June the days are long.", "Im Juni sind die Tage lang."), e("June smells of summer.", "Der Juni riecht nach Sommer.")],
  "de.word.juli": [e("In July we swim in the lake.", "Im Juli schwimmen wir im See."), e("July is warm and bright.", "Der Juli ist warm und hell.")],
  "de.word.august": [e("In August we are travelling.", "Im August verreisen wir."), e("August is harvest time.", "Der August ist Erntezeit.")],
  "de.word.september": [e("In September school starts.", "Im September beginnt die Schule."), e("September brings cool evenings.", "Der September bringt kühle Abende.")],
  "de.word.oktober": [e("In October the leaves fall.", "Im Oktober fallen die Blätter."), e("October is colourful.", "Der Oktober ist bunt.")],
  "de.word.november": [e("In November it gets dark early.", "Im November wird es früh dunkel."), e("November is quiet and grey.", "Der November ist still und grau.")],
  "de.word.dezember": [e("In December we bake cookies.", "Im Dezember backen wir Plätzchen."), e("December ends the year.", "Der Dezember beendet das Jahr.")],
  "de.word.waehrend": [e("During the night it rained.", "Während der Nacht regnete es."), e("During the week I work.", "Während der Woche arbeite ich.")],
  "de.word.uebermorgen": [e("The day after tomorrow is a holiday.", "Übermorgen ist ein Feiertag."), e("We are meeting the day after tomorrow.", "Wir treffen uns übermorgen.")],
  "de.chunk.auf-jeden-fall": [e("In any case, take an umbrella.", "Nimm auf jeden Fall einen Schirm."), e("That helps in any case.", "Das hilft auf jeden Fall.")],
  "de.chunk.zum-glueck": [e("Luckily nothing happened.", "Zum Glück ist nichts passiert."), e("Luckily we were early.", "Zum Glück waren wir früh dran.")],
  "de.word.bahnhof": [e("The train station is old but beautiful.", "Der Bahnhof ist alt, aber schön."), e("We are meeting at the train station.", "Wir treffen uns am Bahnhof.")],
  "de.word.flughafen": [e("The airport is huge.", "Der Flughafen ist riesig."), e("The bus drives to the airport.", "Der Bus fährt zum Flughafen.")],
  "de.word.hotel": [e("The hotel is by the sea.", "Das Hotel liegt am Meer."), e("A small hotel in the old town.", "Ein kleines Hotel in der Altstadt.")],
  "de.word.restaurant": [e("The restaurant opens at six.", "Das Restaurant öffnet um sechs."), e("We are eating at the restaurant today.", "Wir essen heute im Restaurant.")],
  "de.word.markt": [e("The market smells of fresh bread.", "Der Markt riecht nach frischem Brot."), e("Flowers from the market.", "Blumen vom Markt.")],
  "de.word.kirche": [e("The church stands in the centre.", "Die Kirche steht im Zentrum."), e("An old church made of stone.", "Eine alte Kirche aus Stein.")],
  "de.word.krankenhaus": [e("The hospital is new.", "Das Krankenhaus ist neu."), e("She works at the hospital.", "Sie arbeitet im Krankenhaus.")],
  "de.word.bibliothek": [e("The library closes at eight.", "Die Bibliothek schließt um acht."), e("I am studying at the library.", "Ich lerne in der Bibliothek.")],
  "de.word.garten": [e("The garden smells of roses.", "Der Garten duftet nach Rosen."), e("The children are playing in the garden.", "Die Kinder spielen im Garten.")],
  "de.word.park": [e("We are walking through the park.", "Wir spazieren durch den Park."), e("The park is old and quiet.", "Der Park ist alt und still.")],
  "de.word.wetter": [e("The weather is changing quickly.", "Das Wetter wechselt schnell."), e("What will the weather be tomorrow?", "Wie wird das Wetter morgen?")],
  "de.word.sonne": [e("The sun rises early.", "Die Sonne geht früh auf."), e("We are sitting in the sun.", "Wir sitzen in der Sonne.")],
  "de.word.schnee": [e("The snow is melting already.", "Der Schnee schmilzt schon."), e("Children love snow.", "Kinder lieben Schnee.")],
  "de.word.wind": [e("The wind is turning.", "Der Wind dreht sich."), e("A warm wind from the south.", "Ein warmer Wind aus dem Süden.")],
  "de.word.vorgestern": [e("The letter came the day before yesterday.", "Der Brief kam vorgestern."), e("The day before yesterday it snowed.", "Vorgestern hat es geschneit.")],
  "de.word.berg": [e("The mountain is covered in snow.", "Der Berg ist voller Schnee."), e("We are climbing the mountain.", "Wir steigen auf den Berg.")],
  "de.word.fluss": [e("The river flows to the sea.", "Der Fluss fließt zum Meer."), e("A bridge over the river.", "Eine Brücke über den Fluss.")],
  "de.word.see": [e("The lake glitters in the sun.", "Der See glitzert in der Sonne."), e("We are swimming in the lake.", "Wir schwimmen im See.")],
  "de.word.meer": [e("The sea roars loudly.", "Das Meer rauscht laut."), e("A house by the sea.", "Ein Haus am Meer.")],
  "de.word.wald": [e("The forest smells of rain.", "Der Wald riecht nach Regen."), e("We are hiking through the forest.", "Wir wandern durch den Wald.")],
  "de.word.baum": [e("The tree loses its leaves.", "Der Baum verliert seine Blätter."), e("A bird sits in the tree.", "Ein Vogel sitzt im Baum.")],
  "de.word.blume": [e("The flower blooms red.", "Die Blume blüht rot."), e("A flower stands in the vase.", "Eine Blume steht in der Vase.")],
  "de.word.vogel": [e("The bird flies south.", "Der Vogel fliegt nach Süden."), e("A small bird is singing.", "Ein kleiner Vogel singt.")],
  "de.word.katze": [e("The cat sleeps on the chair.", "Die Katze schläft auf dem Stuhl."), e("Our cat likes milk.", "Unsere Katze mag Milch.")],
  "de.word.pferd": [e("The horse eats an apple.", "Das Pferd frisst einen Apfel."), e("A horse stands in the field.", "Ein Pferd steht auf der Wiese.")],
  "de.word.fisch": [e("The fish swims deep.", "Der Fisch schwimmt tief."), e("Fresh fish from the market.", "Frischer Fisch vom Markt.")],
  "de.word.kopf": [e("My head needs a break.", "Mein Kopf braucht eine Pause."), e("He nods his head.", "Er nickt mit dem Kopf.")],
  "de.word.auge": [e("My right eye itches.", "Mein rechtes Auge juckt."), e("The eye needs light.", "Das Auge braucht Licht.")],
  "de.word.ohr": [e("My ear hurts.", "Mein Ohr tut weh."), e("He whispers in her ear.", "Er flüstert ihr ins Ohr.")],
  "de.word.nase": [e("My nose is running.", "Meine Nase läuft."), e("The dog has a fine nose.", "Der Hund hat eine feine Nase.")],
  "de.word.mund": [e("The child opens its mouth.", "Das Kind öffnet den Mund."), e("He keeps his mouth shut.", "Er hält den Mund.")],
  "de.word.herz": [e("My heart is beating calmly.", "Mein Herz schlägt ruhig."), e("A heart of gold.", "Ein Herz aus Gold.")],
  "de.word.arzt": [e("The doctor is helping quickly.", "Der Arzt hilft schnell."), e("I have an appointment at the doctor's.", "Ich habe einen Termin beim Arzt.")],
};

// Merge + authoring guards: fail the build loudly instead of shipping a
// sentence the engine can't use.
{
  const missing = [];
  for (const item of items) {
    const extras = extraExamples[item.id];
    if (!extras) { missing.push(item.id); continue; }
    const forms = item.sourceForms.map((f) => f.form.toLowerCase());
    for (const ex of extras) {
      if (!ex.target.toLowerCase().includes(item.target.toLowerCase()))
        throw new Error(`${item.id}: extra target "${ex.target}" lacks citation form "${item.target}"`);
      const src = ex.source.toLowerCase();
      if (!forms.some((f) => src.includes(f)))
        throw new Error(`${item.id}: extra source "${ex.source}" contains no source form (cloze needs one)`);
      const tokens = ex.target.split(/\s+/).filter(Boolean).length;
      if (tokens < 3 || tokens > 10)
        throw new Error(`${item.id}: extra target "${ex.target}" has ${tokens} tokens (rebuild wants 3–10)`);
      item.examples.push(ex);
    }
  }
  if (missing.length) throw new Error(`items without extra examples: ${missing.join(", ")}`);
}

const pack = {
  schema: 1,
  language: "de",
  version: "2026.09",
  provenance: {
    corpus: "hand-curated seed + model-authored expansion, frequency-informed (full FrequencyWords/OpenSubtitles pipeline pending)",
    license: "project-original content",
    packtool: "seed-generator-2.0",
    authoringModel: "claude-fable-5 (bands 5-10 + additions; human spot-review: docs/pack-review-2026.08.md)",
    generatedAt: "2026-07-14",
  },
  grading: { articles: ["der", "die", "das", "ein", "eine"] },
  items,
};

process.stdout.write(JSON.stringify(pack, null, 2) + "\n");
